# Generated by Django 3.2.9 on 2021-12-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_test_app', '0002_auto_20211229_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
