# Generated by Django 3.2.9 on 2021-12-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_test_app', '0003_userinfo_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
